# Generated by Django 4.2.7 on 2024-01-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('label', models.CharField(choices=[('1', 'Income'), ('2', 'Expense')], default='1', max_length=20)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
