# Generated by Django 4.2.7 on 2024-01-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_wallets_alter_transactions_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallets',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
